### ISSUE TITLE
Scrolling in popup is glitchy

### ISSUE THREAD

**Issue by mjiang108** [ainzacruz/xTabby#5]
# Steps to reproduce 
1. Have enough tabs open so that you have to scroll on the popup.
2. When you scroll, only a portion of the popup scrolls. The rest of it remains frozen.
3. Disabling and enabling the extension or quitting and restarting chrome will fix the issue temporarily but it comes back.

***This glitchy scrolling happens all the time for me, but not for 2 other people who have tested it, so it may just be a local machine issue. Please leave a comment here if you encounter this bug too.***

# Other notes
- happens even on a very early commit 0e8d9523b8b6cb8178d1eff5d18e325911de0451
- happens on fullscreen and non-fullscreen
- seems to affect a specific browser window: if you have two open, one may have issue and one may be fine

# Screenshot(s)
<img width="619" alt="Screen Shot 2021-03-13 at 2 49 51 AM" src="https://user-images.githubusercontent.com/9983876/111028042-d8cd2700-83a8-11eb-92f5-cfb5863059b3.png">

**Comment by ainzacruz** [comment]
This has been resolved.

**Comment by mjiang108** [comment]
Resolved, it was just a local machine issue.
